// <auto-generated />
using System;
using HogarGestor.App.Pericistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Persistencia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HogarGestor.App.Dominio.Familiar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Familiares");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.HistoriaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FamiliarId")
                        .HasColumnType("int");

                    b.Property<int?>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int?>("NinoId")
                        .HasColumnType("int");

                    b.Property<int?>("SugerenciasCuidadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamiliarId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("NinoId");

                    b.HasIndex("SugerenciasCuidadoId");

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Especialidad")
                        .HasColumnType("int");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistroRethus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Nino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<float>("Latitud")
                        .HasColumnType("real");

                    b.Property<float>("Longitud")
                        .HasColumnType("real");

                    b.Property<DateTime>("Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatronesCrecimientoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatronesCrecimientoId");

                    b.ToTable("Ninos");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.PatronesCrecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("Patron")
                        .HasColumnType("int");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PatronesCrecimientos");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.RegistroHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("PatronesCrecimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatronesCrecimientoId");

                    b.ToTable("RegistrosHistoricos");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.SugerenciasCuidado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SugerenciasCuidados");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.HistoriaClinica", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.Familiar", "Familiar")
                        .WithMany()
                        .HasForeignKey("FamiliarId");

                    b.HasOne("HogarGestor.App.Dominio.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId");

                    b.HasOne("HogarGestor.App.Dominio.Nino", "Nino")
                        .WithMany()
                        .HasForeignKey("NinoId");

                    b.HasOne("HogarGestor.App.Dominio.SugerenciasCuidado", "SugerenciasCuidado")
                        .WithMany()
                        .HasForeignKey("SugerenciasCuidadoId");

                    b.Navigation("Familiar");

                    b.Navigation("Medico");

                    b.Navigation("Nino");

                    b.Navigation("SugerenciasCuidado");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.Nino", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.PatronesCrecimiento", "PatronesCrecimiento")
                        .WithMany()
                        .HasForeignKey("PatronesCrecimientoId");

                    b.Navigation("PatronesCrecimiento");
                });

            modelBuilder.Entity("HogarGestor.App.Dominio.RegistroHistorico", b =>
                {
                    b.HasOne("HogarGestor.App.Dominio.PatronesCrecimiento", "PatronesCrecimiento")
                        .WithMany()
                        .HasForeignKey("PatronesCrecimientoId");

                    b.Navigation("PatronesCrecimiento");
                });
#pragma warning restore 612, 618
        }
    }
}
